version: "3.8"

services:
  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mi_contrasena
      MYSQL_DATABASE: tienda
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Servicio de la aplicación Spring Boot
  tienda-app:
    build: .
    container_name: tienda-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mi_contrasena
    volumes:
      - imagenes_productos:/app/images

volumes:
  mysql_data:
  imagenes_productos: