spring:
  application:
    name: tienda
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialize: true
    #data: classpath:data.sql
    #schema: classpath:schema.sql
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/tienda
    username: root
    password: mi_contrasena
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      #max-request-size: 2MB
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org:
#      springframework: DEBUG
jwt-util:
  time-in-minutes: 10
file:
  upload-dir: /app/images